// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBPew0so6JC6NK-y-_EHJAMziR4DqnyOi8',
    appId: '1:846782377410:web:89b8e1fa5862a9e91a3a5b',
    messagingSenderId: '846782377410',
    projectId: 'study-app-f5620',
    authDomain: 'study-app-f5620.firebaseapp.com',
    storageBucket: 'study-app-f5620.appspot.com',
    measurementId: 'G-WJE4E0MMMM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCganYpDSQFrssyEu6iCbyR2II5bVLu3Nc',
    appId: '1:846782377410:android:f4cb16826a6549f91a3a5b',
    messagingSenderId: '846782377410',
    projectId: 'study-app-f5620',
    storageBucket: 'study-app-f5620.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBXRBc497qbpIGzeqh7esBkG0a7D9Q8Kqw',
    appId: '1:846782377410:ios:0d8afcce998acb9e1a3a5b',
    messagingSenderId: '846782377410',
    projectId: 'study-app-f5620',
    storageBucket: 'study-app-f5620.appspot.com',
    iosBundleId: 'com.example.flutterStudyApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBXRBc497qbpIGzeqh7esBkG0a7D9Q8Kqw',
    appId: '1:846782377410:ios:229abf32757445761a3a5b',
    messagingSenderId: '846782377410',
    projectId: 'study-app-f5620',
    storageBucket: 'study-app-f5620.appspot.com',
    iosBundleId: 'com.example.flutterStudyApp.RunnerTests',
  );
}
